### PR TITLE
Fixed toggleCheck and remove bug

### LINKED ISSUE #5384: Toggle select is broken
**1.18.0**:

**Description**  
click to toggle select is broken (_toggleCheck)

**Example**  
https://live.bootstrap-table.com/code/fvaletas/5113

Reorder column "Item name twice" (item 9 is now the first one),
Select item 9 then click getSelections button
=> Item0 is selected

**Possible  (optional)**  
bootstrap-table.js line 7299 : var row = this.options.data[index];
this.options.data is the original data, not the sorted one

### LINKED ISSUE #5403: Incorrect row unchecked on unchecking after applying search filter.
**Bootstraptable version(s) affected**: v1.18.0

**Description**  
Steps to reproduce: 
1. Select all rows using checkbox.
2. Search for some keyword.
3. Uncheck a row from the search results.
4. Clear search box.
5. The table unchecks using index, not value. So, if first row was unchecked from search results, then first row is also unchecked from selections made in Step 1.

**Example**  
https://live.bootstrap-table.com/code/supmanyu/5191

### LINKED ISSUE #5420: getSelections doesn't work as expected
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
When using data-search on table or data-sortable on column, the returned value(s) is/are not correct.

**Example**  
On the [getSelections example](https://live.bootstrap-table.com/example/methods/get-selections.html), just enter 5 on the search input, select the first line (5) and click on getSelections button. 
It will display id 0 (and not 5 as expected)

### LINKED ISSUE #5429: replacement for getAllSelections ?
**Bootstraptable version(s) affected**:
>1.18.0

**Description**  
getSelections doesn't return correct rows when the table is filtered by the search field. My solution was getAllSelections but this method was removed with 1.18.0. Is there any replacement or workaround ?

**Example**  

**Possible  (optional)**  

**Additional context**

### PR DESCRIPTION
**Pull request by wenzhixin**
**Bug fix?**
yes

**New Feature?**
no

### Fix #5298 

* Bug 1:
1. Check the first checkbox, delete the row.
2. Do the same for the second row => Deletion is not working

* Bug 2:
1. Check the first checkbox, delete the row.
2. Click on `getSelections`, there is still the removed row.

Before: https://live.bootstrap-table.com/code/UtechtDustin/4645
After: https://live.bootstrap-table.com/code/wenzhixin/5403
     
### Fix #5403

1. Select all rows using checkbox.
2. Search for some keyword.
3. Uncheck a row from the search results.
4. Clear search box.

Before: https://live.bootstrap-table.com/code/supmanyu/5191
After: https://live.bootstrap-table.com/code/wenzhixin/5405

### Fix #5384 

* Bug 1:
1. Reorder column "Item name twice" (item 9 is now the first one)
2. Select item 9 then click getSelections button

Before: https://live.bootstrap-table.com/code/fvaletas/5113
After: https://live.bootstrap-table.com/code/wenzhixin/5406

* Bug 2:
1. Click the `removeByUniqueId`.
2. Click the `getData`.

Before: https://live.bootstrap-table.com/code/wenzhixin/5407
After: https://live.bootstrap-table.com/code/wenzhixin/5408

### Fix #5420 

1. Click the `Amount` column.
2. Select the first three rows.
3. Click the `getSelections`.

Before: https://live.bootstrap-table.com/code/manukieli/5302
After: https://live.bootstrap-table.com/code/wenzhixin/5409
Before: https://live.bootstrap-table.com/code/manukieli/5301
After: https://live.bootstrap-table.com/code/wenzhixin/5410

### Fix #5429 

1. search for e.g. "3"
2. check both appearing rows
3. clear the search field
4. the first two rows in the table are checked and not the rows from the previous selection

Before: https://live.bootstrap-table.com/example/options/maintain-meta-data.html
After: https://live.bootstrap-table.com/code/wenzhixin/5411

### CODE REVIEW

**Comment by wenzhixin** [comment]
Ref #5298, #5414

File: src/bootstrap-table.js [hunk 1]
```diff
@@ -2542,6 +2541,7 @@ class BootstrapTable {
 
     if (row) {
       this.options.data.splice(this.options.data.indexOf(row), 1)
```
Comment (djhvscf) [inline src/bootstrap-table.js:2543]: Should we alter the original data array?

**Review by djhvscf — CHANGES_REQUESTED** [review]

File: src/bootstrap-table.js (hunk 1 above)
Comment (wenzhixin) [reply src/bootstrap-table.js]: Updated the logic of the `removeByUniqueId` method to the same as the `remove` method.

**Review by djhvscf — APPROVED** [review]

**Comment by empouras** [comment]
Do we know when this will be merged to "dist" folder? Is there a new version coming?

**Comment by UtechtDustin** [comment]
@wenzhixin Could you release a new version :-) ?

**Comment by wenzhixin** [comment]
OK

**Comment by saurabhsharma2u** [comment]
is this included on ver 1.18.1 ?

**Comment by djhvscf** [comment]
@saurabhsharma2u you can check the release notes. https://bootstrap-table.com/news/#core

**Comment by saurabhsharma2u** [comment]
@djhvscf thank you, i cross checked the core release,
Update: Fixed toggleCheck, getSelections and remove bug.

this is not working with 1.18.1 (with search and pagination)

**Comment by djhvscf** [comment]
@saurabhsharma2u could you elaborate more what is not working?

**Comment by empouras** [comment]
I think now a new issue is created....
When in the column of checkboxes I add a dataformatter, I always get a "-" in the column

image

**Comment by UtechtDustin** [comment]
@empouras Please provide us an example using our [editor](https://live.bootstrap-table.com/).
But why do you try to use a formatter on a checkbox column ?

**Comment by empouras** [comment]
I use the formatter as a call to a javascript method so I will disable some of the checkboxes according to some row value

**Comment by UtechtDustin** [comment]
@empouras i think you mean this bug:  https://live.bootstrap-table.com/example/column-options/checkbox-disabled.html ?
It look like we already fixed that bug in our develop Branch, check this example: https://live.bootstrap-table.com/code/UtechtDustin/6319

So please wait for the next release.

**Comment by empouras** [comment]
It looks exactly like the bug I am talking about. Today I downloaded the 1.18.1 to get the fix of the toggle bug but then I got this one :)! Do we know when the next release will be? About...?
P.S: Thank you for the fast response

**Comment by UtechtDustin** [comment]
@wenzhixin Do you already planned the next release ?

**Comment by empouras** [comment]
Another thing as well that would be nice to fix is the select all button when pagination. Since then it selects only from the first page. It would be nice to select all and keep in memory which ones are selected through the pagination as well. 
Just food for thought ;)

**Comment by UtechtDustin** [comment]
Do you mean the option [maintainMetaData](https://bootstrap-table.com/docs/api/table-options/#maintainmetadata) ?
Example: https://live.bootstrap-table.com/example/options/maintain-meta-data.html

**Comment by empouras** [comment]
Even at this example if you are on page 1 and click on select all checkbox...what do you expect. I expect all data selected in all pages. Not just the first page. The fact that we use pagination is if we have a lot of data. So when you want to select all of the rows in all pages you should be able to do it with the select all checkbox. Otherwise you have to do that for every page in pagination. Really annoying and tiresome :)

**Comment by UtechtDustin** [comment]
> It would be nice to select all and keep in memory which ones are selected through the pagination as well.
I thought you meant the "memory issue".

I guess this would be a good feature, could you please open a issue for that ? :-)

**Comment by empouras** [comment]
Any news about a new release?

**Comment by UtechtDustin** [comment]
@empouras do you mean for this PR or for #5560 ?
This PR should be in the newest version.

**Comment by empouras** [comment]
I mean this...

image

**Comment by UtechtDustin** [comment]
It's fixed in the newest version.
