### PR TITLE
fix/5282

### LINKED ISSUE #5282: Duplicated data when adding rows to empty tables
**Bootstraptable version(s) affected**:
1.17.1

**Description** 
After using the method "insertRow" to add data to an empty table, if you use it again to add a row to another empty table, the data will be duplicated.

**Example**  

Steps to reproduce:
1. Press the button "insertRow" from the first table
2. Press the button "insertRow" from the second table
3. New data from first table is also added to the second table

https://live.bootstrap-table.com/code/joaossantos/4558

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5282

**Example(s)?**
Before: https://live.bootstrap-table.com/code/joaossantos/4558
After: https://live.bootstrap-table.com/code/UtechtDustin/4658

### CODE REVIEW

File: src/bootstrap-table.js [hunk 1]
```diff
@@ -192,6 +192,10 @@ class BootstrapTable {
       })
     })
 
+    if (this.options.data.length === 0) {
```
Comment (djhvscf) [inline src/bootstrap-table.js:195]: Not sure why this line fix the sync between two tables

**Review by djhvscf — CHANGES_REQUESTED** [review]

File: src/bootstrap-table.js (hunk 1 above)
Comment (UtechtDustin) [reply src/bootstrap-table.js:195]: I'm also not sure, but without that javascript will use a shared array.
You also dont have the issue if one of the table have data (one row is enough), because there use not shared arrays.

Comment (djhvscf) [reply src/bootstrap-table.js:195]: So, if we change something in this.options both tables will be affected?

Comment (UtechtDustin) [reply src/bootstrap-table.js:195]: This only occurs in this edge case (Both table has no init data(rows) also this only happens with `this.options.data`.

Comment (djhvscf) [reply src/bootstrap-table.js:195]: ok, thanks @UtechtDustin . @wenzhixin do you have any idea? I think the fix is good because it is working now but it looks to me like a workaround

Comment (UtechtDustin) [reply src/bootstrap-table.js:195]: Just a explanation for you @djhvscf, if you do
```
let x = []
let y = x
y.push('test')
alert(x)
```
Example: https://live.bootstrap-table.com/code/UtechtDustin/4659

You will see `test`, because javascript dont copy the array. Instead of a copying, javascript will set the internal reference/pointer of the array (variable x) to variable y. Which means both variables share the same array.

I'm not sure where this happens in the bootstrap-table so this PR is just a workaround to prevent bugs.

Comment (djhvscf) [reply src/bootstrap-table.js:195]: Yes, i know that. But we should remove those kind of problems since every table should be isolated

Comment (UtechtDustin) [reply src/bootstrap-table.js:195]: oh okay, i thought you dont know that because of you question :D
> So, if we change something in this.options both tables will be affected?

Comment (wenzhixin) [reply src/bootstrap-table.js:195]: Thanks, @UtechtDustin and @djhvscf , I will check this problem.

**Comment by wenzhixin** [comment]
I find the problem, if `options.data` of the table is not set, it will use `DEFAULTS.data` by default, they are the same.

**Review by djhvscf — APPROVED** [review]
