### PR TITLE
Fix print with rowspan / colspan

### LINKED ISSUE #5206: Printing not working correctly for grouped columns
**Bootstraptable version(s) affected**: 17.1

**Description**  
When the table has a group column, the print output fills in a  '-' for the first group column and extends the table by one column. 

**Example**  
https://live.bootstrap-table.com/code/GCru/4115

### PR DESCRIPTION
**Pull request by Moutard3**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5206

**Example(s)?**
Before: https://live.bootstrap-table.com/code/GCru/4115 (1.17) / https://live.bootstrap-table.com/code/Moutard3/5156 (1.18)
After: https://live.bootstrap-table.com/code/Moutard3/5155 (moutard3:fix/5206)

### CODE REVIEW

File: src/extensions/print/bootstrap-table-print.js [hunk 1]
```diff
@@ -269,9 +276,12 @@ $.BootstrapTable = class extends $.BootstrapTable {
     const newWin = window.open('')
 
     newWin.document.write(this.options.printPageBuilder.call(this, table))
+    /*
```
Comment (djhvscf) [inline src/extensions/print/bootstrap-table-print.js:279]: Please uncomment these lines of code

**Review by djhvscf — APPROVED** [review]

**Review by djhvscf — CHANGES_REQUESTED** [review]
Please uncomment the lines 279 - 285

**Comment by Moutard3** [comment]
Sorry about that, though I did, but it wasn't added before commit

**Review by wenzhixin — APPROVED** [review]
