### PR TITLE
Fixed icons

### LINKED ISSUE #5323: change autoRefresh icon bug
**Bootstraptable version(s) affected**:

**Description**  

**Example**  

https://live.bootstrap-table.com/code/JupiterMx/4871

**Possible  (optional)**  

**Additional context**

### LINKED ISSUE #5325: How to change to multiSort Icons ?
**Description**  
Running the current version 1.18.0 i have the following problem:

i would like to change the icon of the multi-sort button in the upper right.

normally (for the other buttons) i am able to do it by
```js
iconsPrefix: "",
icons: {
     refresh: "las la-sync",
```

Due to logic (and some thin documentation) i should be:
```js
     multipleSort: "las la-sort",
OR
     multi-sort: "las la-sort",
OR
     multiSort: "las la-sort",
OR
     multisort: "las la-sort",
```

But i found no way to change the glyphicon with my icon for this extension.
Also trying with "Icons", "Icon" changed nothing.

I was able to change the popup info with following code:
```js
formatMultipleSort: function formatAutoRefresh() {
     return "Eigener Text";
},
```

### LINKED ISSUE #5327: Multisort: showMultiSortButton without effect
**Bootstraptable version(s) affected**:
Current version (1.18.0)

**Description**  
Setting the option "showMultiSortButton" to "false" is without effect
Also when disbaling the multisort in general with "showMultiSort: false"

**Example**  
https://live.bootstrap-table.com/code/snoopy72/4874

**Possible  (optional)**  
When disable the button, it should not be shown :)

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5323 
Fix #5325
Fix #5327

**Example(s)?**
#5323:
Before: https://live.bootstrap-table.com/code/JupiterMx/4871
After: https://live.bootstrap-table.com/code/UtechtDustin/4876

#5325
Before: https://live.bootstrap-table.com/code/UtechtDustin/4877
After: https://live.bootstrap-table.com/code/UtechtDustin/4878

#5327
Before: https://live.bootstrap-table.com/code/UtechtDustin/4880
After: https://live.bootstrap-table.com/code/UtechtDustin/4881

### CODE REVIEW

**Review by djhvscf — APPROVED** [review]

File: src/extensions/multiple-sort/bootstrap-table-multiple-sort.js [hunk 1]
```diff
@@ -7,13 +7,42 @@
...
+  plus: {
+    bootstrap3: 'glyphicon-plus',
+    bootstrap4: 'fa-plus',
+    bootstrap5: 'fa-plus',
+    semantic: 'fa-plus',
+    materialize: 'plus',
+    foundation: 'fa-plus',
+    bulma: 'fa-plus',
+    'bootstrap-table': 'icon-plus'
+  }[$.fn.bootstrapTable.theme] || 'fa-clock',
```
Comment (wenzhixin) [inline src/extensions/multiple-sort/bootstrap-table-multiple-sort.js:21]: || 'fa-clock' can be removed.
