### PR TITLE
Fix/6128

### LINKED ISSUE #6128: Filter Control of input type - Filter by various values
### Description

I have a bootstrap table which has like 4 columns.

Imagine one of those columns is called 'car type' and I want to search both sedans and coupes.

What combination of chars should I insert in the search input so it looks for those two? Is this even possible?

### Example(s)

`sedan|coupe` `sedan&coupe` `sedan,coupe` `sedan, coupe`

imagen

### PR DESCRIPTION
**Pull request by UtechtDustin**
**🤔Type of Request**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

Fix #6128

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

Added two new options `filterControlMultipleSearch` and `filterControlMultipleSearchDelimiter` to the filter-control extension, to allow filtering multiple values at once.  

**💡Example(s)?**
Search for `Item 1,Item 2`
Before: https://live.bootstrap-table.com/code/UtechtDustin/12267
After: https://live.bootstrap-table.com/code/UtechtDustin/12269

Search for `Item 1|Item 2`
Before: https://live.bootstrap-table.com/code/UtechtDustin/12267
After: https://live.bootstrap-table.com/code/UtechtDustin/12270

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: src/extensions/filter-control/bootstrap-table-filter-control.js [hunk 1]
```diff
@@ -225,57 +227,61 @@ $.BootstrapTable = class extends $.BootstrapTable {
...
-                  [value, item, i],
-                  value
-                )
-              }
+          let filterValues = [filterValue]
+
+          if (
+            this.options.filterControlMultipleSearch
+          ) {
+            filterValues = filterValue.split(this.options.filterControlMultipleSearchDelimiter)
```
Comment (djhvscf) [inline src/extensions/filter-control/bootstrap-table-filter-control.js:235]: I think it should trim spaces before and after the comma because if I put this Item 1, Item 2 it doesn't work

Comment (djhvscf) [inline src/extensions/filter-control/bootstrap-table-filter-control.js:235]: I think it should trim spaces before and after the comma because if I put this Item 1, Item 2 it doesn't work

**Review by djhvscf — CHANGES_REQUESTED** [review]

File: src/extensions/filter-control/bootstrap-table-filter-control.js (hunk 1 above)
Comment (UtechtDustin) [reply src/extensions/filter-control/bootstrap-table-filter-control.js:235]: Makes sense, done!

**Review by djhvscf — APPROVED** [review]

**Comment by AndresConpas** [comment]
Thank you a lot for this feature guys, I think it will be very useful to everyone!

**Comment by UtechtDustin** [comment]
@astomas No this is not normal.
@wenzhixin the sass call will return a 500er

**Comment by wenzhixin** [comment]
> @astomas No this is not normal. @wenzhixin the sass call will return a 500er

Fixed
