### PR TITLE
Fix search text overwritting

### LINKED ISSUE #2203: Filter-control and server side pagination
A have server side pagination grid with search control and I wan't to add filter control working on client-side (filter only what is visible). It's possible?
Now when add some text to input filter column, there is server side refresh and entered text is sended same as search text.

### PR DESCRIPTION
**Pull request by UtechtDustin**
Only set the search text if it was triggered by the original search input to prevent overwriting the search text (e.g. for the filter-control extension).

fix #2203 
Demo: http://jsfiddle.net/6nt0wxpy/4/

### CODE REVIEW

File: src/bootstrap-table.js [hunk 1]
```diff
@@ -685,8 +685,10 @@ class BootstrapTable {
         return
       }
 
-      this.searchText = text
-      this.options.searchText = text
+      if ($(currentTarget).hasClass('search-input')) {
```
Comment (djhvscf) [inline src/bootstrap-table.js]: this.options.search is not an option here?

Comment (UtechtDustin) [reply src/bootstrap-table.js]: No is not an option, because i have to check if the input which triggered the search is an input for the filter-control extension or the normal search input.
With `this.options.search` i only know if the search is enabled or not.
