### PR TITLE
fixes #611 - Add spanish (España) translation.

### LINKED ISSUE #611: Acute accent in Spanish locale file.
Hi !!

I've built a file with Spanish (España) translation (bootstrap-table-es-SP.js) but the accent symbols doesn't appears correctly, What's wrong? (have a look the attach).

I don't have a "pull request" of "bootstrap-table-es-SP.js" file because I've never used Github and I don't know how I have to do it ... sorry ;-)

Thanks in advance.

captura2

captura

### PR DESCRIPTION
**Pull request by anpegar**
- Add spanish (España) translation.
- Fixed vertical alignament between pagination block and pagination-detail block.

### CODE REVIEW

File: src/bootstrap-table.js [hunk 1]
```diff
@@ -810,7 +810,8 @@
                 .off('click').on('click', function () {
                     that.options.cardView = !that.options.cardView;
                     that.initHeader();
-                    that.initToolbar();
```
Comment (djhvscf) [inline src/bootstrap-table.js]: Why this change? @anpegar

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/toolbar
Need some docs or example, can you help to add a README.md file?

File: src/bootstrap-table.js (hunk 1 above)
Comment (anpegar) [inline src/bootstrap-table.js]: Hi, again !!

I've found another error. In "BootstrapTable.prototype.initBody = function (fixedScroll) { ..." It's necessary add the styles of checkbox header to your cell so I've changed this line:
`<div class="card-view">' : sprintf('<td class="bs-checkbox" %s>',style), // Add styles to checkbox cell.`

.
captura
