### PR TITLE
Fixed reorder row bug when side-pagination is server

### LINKED ISSUE #6698: data-side-pagination="server" and reorder row
### Bootstraptable version(s) affected

1.21.3

### Description

after a long investigation a found the reason because reorder row was not working in my app and it was related of that attribute data-side-pagination="server". 
there is  a reason ? 
can you note in the doc please for other users ? 
thanks 

### Example(s)

_No response_

### Possible Solutions

remove data-side-pagination="server" os use "client"

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fish-fly**
**🤔Type of Request**
- [x] **Bug fix**
- [ ] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**
Fix #6698 

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

Fixed reorder row bug when side-pagination is server

**💡Example(s)?**
* Bug: https://live.bootstrap-table.com/code/fish-fly/14844
* Fixed: https://live.bootstrap-table.com/code/fish-fly/14845

**☑️Self Check before Merge**

⚠️ Please check all items below before reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: src/extensions/reorder-rows/bootstrap-table-reorder-rows.js [hunk 1]
```diff
@@ -126,6 +126,10 @@ $.BootstrapTable = class extends $.BootstrapTable {
   initSearch () {
     this.ignoreInitSort = true
     super.initSearch()
+
+    if (this.options.sidePagination === 'server') {
+      this.data = [...this.options.data]
+    }
```
Comment (wenzhixin) [inline src/extensions/reorder-rows/bootstrap-table-reorder-rows.js:132]: The changes here may affect other extensions.

Comment (wenzhixin) [reply src/extensions/reorder-rows/bootstrap-table-reorder-rows.js:132]: Move to line 117:

```js
    this.initSearch()

    if (this.options.sidePagination === 'server') {
      this.data = [...this.options.data]
    }
```

**Review by wenzhixin — APPROVED** [review]
